### ISSUE TITLE
Noobnee

### ISSUE THREAD

**Issue by Ade-Pyaar** [noornee/todo-app#2]
Deploy the web app, let's see how it looks.
And no, I can't clone it to my system and run it there.
😏

**Comment by noornee** [comment]
😂 💔 REST "oyapyarpyar"
yeahh right, you don't have the secret key 🙃
alright man, thanks! ... would soon do that, still styling the pages and whatnot 😂

**Comment by Ade-Pyaar** [comment]
The council of elders will be waiting.
And it will be wise for you, mortal, not to keep us waiting for so long as the consequences will be dire.

**Comment by noornee** [comment]
😂💔 look who's talking... you're the mortal here 😤
i am a god 😌 so rest and wait but don't get your hopes up, its just there...
